[package]
name = "noise-c"
version = "0.1.0"
authors = ["Priyank Patel <tocubed@gmail.com>"]
build = "build.rs"

[lib]
name = "noise_c"
crate-type = ["staticlib"]

[dependencies]
noise = { git = "https://github.com/tocubed/noise-rs" }

[build-dependencies]
rusty-cheddar = "0.3.0"
regex = "0.2.1"
